# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Cypress tests

on:
  push:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E on chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup npm package
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v2.7.0
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
          config: baseUrl=https:localhost:3000
